### PR TITLE
Use clang-format for code formatting

### PR DESCRIPTION
**Pull request by aobolensk**

### CODE REVIEW

**Comment by aobolensk** [comment]
requires #60

**Comment by allnes** [comment]
> requires #60

merged

**Comment by aobolensk** [comment]
> > requires #60
> 
> merged

after #62, since they conflict with each each other

**Comment by allnes** [comment]
> > > requires #60
> 
> > 
> 
> > merged
> 
> 
> 
> after #62, since they conflict with each each other

merge thank you

**Pull request merged**
